name:                gl-wrapper
version:             0.9
github:              "tkaaad97/gl-wrapper"
license:             BSD3

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- bytestring >=0.9.2.1 && <0.11
- gl >=0.9 && <0.10
- hashable >=1.2.7.0 && <1.4
- linear >=1.10.1.2 && <1.22
- text >=1.2.3.0 && <1.3
- transformers >=0.3.0.0 && <0.6
- vector >=0.12.0.1 && <0.13

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wredundant-constraints
  dependencies: []

executables:
  example1:
    main:                Example1.hs
    source-dirs:         example
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wredundant-constraints
    dependencies:
    - GLFW-b
    - bytestring
    - containers
    - file-embed
    - gl-wrapper
    - string-qq
