name: build docker images

on:
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build-docker-image:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc:
          - "8.2.2"
          - "8.4.4"
          - "8.6.5"
          - "8.8.3"
    steps:
      - name: build
        run: |
          docker login docker.pkg.github.com -u tkaaad97 -p ${{ secrets.GITHUB_TOKEN }}
          docker build -t docker.pkg.github.com/tkaaad97/gl-wrapper/gl-wrapper-ci:ghc-${{ matrix.ghc }} -f docker/Dockerfile.ghc-${{ matrix.ghc }} .
          docker push docker.pkg.github.com/tkaaad97/gl-wrapper/gl-wrapper-ci:ghc-${{ matrix.ghc }}
