name: build

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: build with ghc-${{ matrix.ghc }}

    strategy:
      matrix:
        ghc:
          - "8.2.2"
          - "8.4.4"
          - "8.6.5"
          - "8.8.3"

    runs-on: ubuntu-20.04

    container:
      image: tkaaad97/gl-wrapper-ci:ghc-${{ matrix.ghc }}
      env:
        HOME: /root

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: cache ~/.stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-stack-${{ hashFiles('**/package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-stack-

      - name: stack build
        run: |
          id
          ls -la ~/
          pwd
          stack config set system-ghc --global true
          stack config set install-ghc --global false
          stack config set allow-different-user --global true
          STACK_YAML=stack-ghc-${{ matrix.ghc }}.yaml stack build
